#!/usr/bin/env bash
urls=(
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/en_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/de_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fr_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/es_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pl_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/it_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/ro_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hu_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/cs_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/nl_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/fi_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/hr_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sk_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sl_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/et_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lt_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/pt_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/bg_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/el_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/lv_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/mt_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/sv_2020_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2009.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2010.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2011.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2012.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2013.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2014.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2015.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2016.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2017.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2018.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2019.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2020.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2009_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2010_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2011_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2012_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2013_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2014_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2015_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2016_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2017_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2018_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2019_2.tar
https://dl.fbaipublicfiles.com/voxpopuli/audios/da_2020_2.tar
)
if [ -z $HF_TOKEN ]; then
  echo "please set the token first"
  exit 0
fi

git config --global user.name "Fangjun Kuang"
git config --global user.email "csukuangfj@gmail.com"


git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/voxpopuli hf

n=552
i=0
for url in ${urls[@]}; do
  i=$((i+1))
  echo "$i/$n"
  echo "url: $url"
  name=$(basename $url)
  echo "name: $name"

  if [ ! -f hf/.${name}.done ]; then
    hf lfs-enable-largefiles ./hf
    pushd hf

    curl -C - -SL -O $url -s -w "\rDownloaded: %{size_download} bytes"
    touch .${name}.done
    ls -lh $name
    git lfs track "*.tar"
    git add .
    git commit -m "add $name"
    git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/voxpopuli main
    git lfs prune
    rm -rf ~/.git/lfs
    popd
    rm -rf hf
    git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/voxpopuli hf
  fi
done
