name: arm-numpy

on:
  push:
    branches:
      - master
      - docker

jobs:
  arm-numpy:
    runs-on: ubuntu-latest
    name: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Download numpy 1.21.0
        shell: bash
        run: |
          sudo apt install -qq -y git wget unzip

          wget https://files.pythonhosted.org/packages/66/03/818876390c7ff4484d5a05398a618cfdaf0a2b9abb3a7c7ccd59fe181008/numpy-1.21.0.zip
          unzip numpy-1.21.0.zip

          ls -lh

      - name: Build numpy
        uses: addnab/docker-run-action@v3
        with:
            image: balenalib/raspberrypi3-python:${{ matrix.python-version }}-bullseye-build
            options: |
              --platform linux/arm/v7
              --volume ${{ github.workspace }}/dist:/build
              --volume ${{ github.workspace }}:/workspace
            shell: bash
            run: |
              uname -a
              which python3
              id # root

              cd numpy-1.21.0
              python setup.py bdist_wheel
              ls -lh dist

              ls -lh dist
              cp -v dist/*.whl /build/

      - name: Show files
        shell: bash
        run: |
          ls -lh dist/

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: numpy.zip
          path: ./dist/*.whl
