name: debug-ssh

on:
  push:
    branches:
      - mlx

jobs:
  debug-ssh:
    if: true
    name: ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download mlx
        shell: bash
        run: |
          git clone --depth 1 https://github.com/ml-explore/mlx

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build mlx ${{ matrix.shared }}
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version

          cd mlx
          mkdir build
          cd build
          cmake \
            -D MLX_ENABLE_X64_MAC=ON \
            -D MLX_BUILD_TESTS=OFF \
            -D MLX_BUILD_EXAMPLES=OFF \
            -D MLX_BUILD_METAL=ON \
            -D MLX_BUILD_GGUF=OFF \
            -D MLX_BUILD_SAFETENSORS=OFF \
            -D BUILD_SHARED_LIBS=${{ matrix.shared }} \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_INSTALL_PREFIX=./install \
            ..

          make -j
          make install
          ls -lh install/*
          find ./install
