name: ubuntu

on:
  push:
    branches:
      - test-arm

  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-arm]

    steps:
      - uses: actions/checkout@v4

      - name: Test
        shell: bash
        run: |
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"

      - name: Enable binfmt
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            # see https://github.com/rust-cross/manylinux-cross
            # image: messense/manylinux2014-cross:armv7l-arm64
            image: messense/manylinux_2_28-cross:armv7l-arm64
            shell: bash
            run: |
              find / -maxdepth 4 -type d | grep armv7
              echo "---"
              find / -maxdepth 4 -type d | grep gnueabihf | head -50
              echo "---"

              # SYSROOT=/usr/armv7-unknown-linux-gnueabihf/armv7-unknown-linux-gnueabihf/sysroot
              #
              # ls -lh $SYSROOT
              #
              # strings $SYSROOT/lib/libc.so.6 | grep ^GLIBC
              #
              #
              #
              #
              # cat > test.cc <<'EOF'
              # #include <iostream>
              # #include <vector>
              #
              # int main() {
              #     std::vector<int> v = {1, 2, 3};
              #     std::cout << "hello armv7, size=" << v.size() << std::endl;
              #     return 0;
              # }
              # EOF
              #
              # SYSROOT=/usr/armv7-unknown-linux-gnueabihf/armv7-unknown-linux-gnueabihf/sysroot



              find / -name "*gcc*"

              uname -a
              which gcc

              ls -lh /usr/armv7-unknown-linux-gnueabihf/bin

              export PATH=/usr/armv7-unknown-linux-gnueabihf/bin:$PATH

              export CC=armv7-unknown-linux-gnueabihf-gcc
              export CXX=armv7-unknown-linux-gnueabihf-g++
              export AR=armv7-unknown-linux-gnueabihf-ar
              export RANLIB=armv7-unknown-linux-gnueabihf-ranlib

              armv7-unknown-linux-gnueabihf-gcc --version
              which armv7-unknown-linux-gnueabihf-gcc
              file $(which armv7-unknown-linux-gnueabihf-gcc)

              echo 'int main(){return 0;}' > t.c
              armv7-unknown-linux-gnueabihf-gcc t.c -o t

              file t

              strings t | grep ^GLIBC




