name: ubuntu

on:
  push:
    branches:
      - test-arm

  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-arm]

    steps:
      - uses: actions/checkout@v4

      - name: Test
        shell: bash
        run: |
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"

      - name: Enable binfmt
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/io \
            messense/manylinux2014-cross:armv7l-arm64 \
            bash -c "
              set -e
              uname -m
              which gcc
              file $(which gcc)

              which arm-linux-gnueabihf-gcc
              arm-linux-gnueabihf-gcc --version

              echo 'int main(){return 0;}' > t.c
              arm-linux-gnueabihf-gcc t.c -o t

              file t
              strings t | grep ^GLIBC
            "

      - name: Build
        if: false
        uses: addnab/docker-run-action@v3
        with:
            # see https://github.com/rust-cross/manylinux-cross
            image: messense/manylinux2014-cross:armv7l-arm64
            shell: bash
            run: |
              uname -a
              which gcc

              gcc --version
              g++ --version
              ldd --version

              echo "---"
              file $(which gcc)

              arm-linux-gnueabihf-gcc --version
              arm-linux-gnueabihf-g++ --version

              echo 'int main(){return 0;}' > t.c
              arm-linux-gnueabihf-gcc t.c -o t
              file t
              strings t | grep ^GLIBC




