name: arm

on:
  push:
    branches:
      - test-arm

  workflow_dispatch:

jobs:
  arm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Test
        shell: bash
        run: |
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"

      - name: Enable binfmt
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            # see https://github.com/rust-cross/manylinux-cross
            # image: messense/manylinux2014-cross:armv7l-arm64
            # image: messense/manylinux_2_28-cross:armv7l-arm64
            # image: messense/manylinux_2_31-cross:armv7l-arm64
            image: quay.io/pypa/manylinux_2_35_armv7l
            shell: bash
            run: |
              find / -maxdepth 4 -type d | grep armv7
              echo "---"
              find / -maxdepth 4 -type d | grep gnueabihf | head -50
              echo "---"

              find / -name libc.so.6

              # /usr/bin/arm-linux-gnueabihf-gcc-11
              # /usr/bin/arm-linux-gnueabihf-gcc
              #
              arm-linux-gnueabihf-gcc --verison

              ls -lh /usr/bin/arm-linux-gnueabihf*
              file /usr/bin/arm-linux-gnueabihf*


              cat > test.cc <<'EOF'
              #include <iostream>
              #include <vector>

              int main() {
                  std::vector<int> v = {1, 2, 3};
                  std::cout << "hello armv7, size=" << v.size() << std::endl;
                  return 0;
              }
              EOF
              find / -name "*gcc*"

              uname -a
              which gcc

              # export CC=armv7-linux-gnueabihf-gcc
              # export CXX=armv7-linux-gnueabihf-g++
              # export AR=armv7-linux-gnueabihf-ar
              # export RANLIB=armv7-linux-gnueabihf-ranlib

              armv7-linux-gnueabihf-gcc --version
              which armv7-linux-gnueabihf-gcc
              file $(which armv7-linux-gnueabihf-gcc)

              echo 'int main(){return 0;}' > t.c
              armv7-linux-gnueabihf-gcc t.c -o t

              file t

              strings t | grep ^GLIBC




