name: test-docker-cpu

on:
  push:
    branches:
      - master

jobs:
  generate_build_matrix:
    # see https://github.com/pytorch/pytorch/pull/50633
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python ./generate_build_matrix.py
          MATRIX=$(python ./generate_build_matrix.py)
          echo "::set-output name=matrix::${MATRIX}"
  build-manylinux-wheels:
    needs: generate_build_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/pytorch/test-infra/blob/9e3d392690719fac85bad0c9b67f530e48375ca1/tools/scripts/generate_binary_build_matrix.py
      # https://github.com/pytorch/builder/tree/main/manywheel
      # https://github.com/pytorch/builder/pull/476
      # https://github.com/k2-fsa/k2/issues/733
      # https://github.com/pytorch/pytorch/pull/50633  (generate build matrix)
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ matrix.image }}
            options: -v ${{ github.workspace }}:/var/www -e PYTHON_VERSION=${{ matrix.python-version }} -e TORCH_VERSION=${{ matrix.torch }} -e CUDA_VERSION=${{ matrix.cuda }}
            run: |
              echo "pwd: $PWD"
              uname -a
              id
              cat /etc/*release
              gcc --version
              python3 --version
              which python3
              cp /var/www/*.sh .

              ./build-cpu.sh

      - name: Display
        shell: bash
        run: |
          ls -lh

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./*.whl

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: github.repository_owner == 'csukuangfj'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/k2 huggingface

          cd huggingface
          git pull
          cp -v ../*.whl ./cpu
          git status
          git lfs track "*.whl"

          git add .

          git commit -m "upload cuda wheel"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/k2 main
          cd ..
          rm -rf huggingface
