name: test-docker-cpu-macos

on:
  push:
    branches:
      - master

jobs:
  generate_build_matrix:
    # see https://github.com/pytorch/pytorch/pull/50633
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python ./generate_build_matrix.py --is-macos
          MATRIX=$(python ./generate_build_matrix.py --is-macos)
          echo "::set-output name=matrix::${MATRIX}"
  build-macos-wheels:
    needs: generate_build_matrix
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - name: Checkout k2
        uses: actions/checkout@v2
        with:
          repository: k2-fsa/k2

      - name: Display
        shell: bash
        run: |
          ls -lh

      # see https://cibuildwheel.readthedocs.io/en/stable/changelog/
      # for a list of versions
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BEFORE_BUILD: pip install torch==${{ matrix.torch}} cmake
          CIBW_BUILD: ${{ matrix.python-version }}-*
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_BUILD_VERBOSITY: 3

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

          ls -lh ./wheelhouse/*.whl

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-macos-latest-cpu
          path: wheelhouse/*.whl

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: github.repository_owner == 'csukuangfj'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/k2 huggingface

          cd huggingface
          git pull
          mkdir -p macos
          cp -v ../wheelhouse/*.whl ./macos
          git status
          git lfs track "*.whl"

          git add .

          git commit -m "upload macos wheel for torch ${{ matrix.torch }} python ${{ matrix.python-version }}"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/k2 main
          cd ..
          rm -rf huggingface
