name: test-ohos

on:
  push:
    branches:
      - ohos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build sherpa-onnx
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/csukuangfj/ohos-standard:latest
            shell: bash
            run: |
              pwd
              id
              cat /etc/*version
              ls -lh
              find / -name hvigorw


