name: torch-android

on:
  push:
    branches:
      - torch2

  workflow_dispatch:

jobs:
  torch-android:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
        torch-version: ["2.3.1"]
        shared_lib: [ON, OFF]

    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v4
        with:
          repository: pytorch/pytorch
          submodules: true
          ref: v${{ matrix.torch-version }}
          path: torch-${{ matrix.torch-version }}

      - name: Install dependencies
        shell: bash
        run: |
          cd torch-${{ matrix.torch-version }}
          pip install -r ./requirements.txt

          sudo apt-get install tree

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Display NDK HOME
        shell: bash
        run: |
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"
          ls -lh ${ANDROID_NDK_LATEST_HOME}

      - name: Build
        shell: bash
        run: |
          cd torch-${{ matrix.torch-version }}
          # https://djl.ai/android/pytorch-native/

          cd scripts
          sed -i.bak s/USE_VULKAN=ON/USE_VULKAN=OFF/g ./build_android.sh
          cd ..
          git diff

          export BUILD_LITE_INTERPRETER=0
          export USE_VULKAN=OFF
          ./scripts/build_pytorch_android.sh arm64-v8a,armeabi-v7a,x86,x86_64

      - name: Display
        shell: bash
        run: |
          cd torch-${{ matrix.torch-version }}
          echo '---build_android_arm64-v8a---'
          ls -lh build_android_arm64-v8a
          tree build_android_arm64-v8a

          echo '---build_android_armeabi-v7a---'
          ls -lh build_android_armeabi-v7a
          tree build_android_armeabi-v7a

          echo '---build_android_x86---'
          ls -lh build_android_x86
          tree build_android_x86

          echo '---build_android_x86_64---'
          ls -lh build_android_x86_64
          tree build_android_x86_64

      - name: Zip
        shell: bash
        run: |
          cd torch-${{ matrix.torch-version }}

          cd build_android_arm64-v8a && zip -r ~/arm64-v8a_native.zip install/include lib && cd ..
          cd build_android_armeabi-v7a && zip -r ~/armeabi-v7a_native.zip install/include lib && cd ..
          cd build_android_x86 && zip -r ~/x86_native.zip install/include lib && cd ..
          cd build_android_x86_64 && zip -r ~/x86_64_native.zip install/include lib && cd ..

          ls -lh *.zip

          mv *native*.zip ..

      - uses: actions/upload-artifact@v4
        with:
          name: torch-${{ matrix.torch-version }}
          path: ./*.zip
