name: torch-linux-aarch64

on:
  push:
    branches:
      - torch2

  workflow_dispatch:
    inputs:
      version:
        description: "Version information (e.g., 2.3.1)"
        required: true

env:
  TORCH_VERSION:
    |- # Enter release tag name or version name in workflow_dispatch. Appropriate version if not specified
    ${{ github.event.release.tag_name || github.event.inputs.version || '2.3.1' }}

jobs:
  linux-aarch64:
    name: ${{ matrix.arch }} ${{ matrix.lib-type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
        lib-type: [shared, static]
        arch: [aarch64]

    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: cache-toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: toolchain
          key: gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -SL -O https://huggingface.co/csukuangfj/sherpa-ncnn-toolchains/resolve/main/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz

          mkdir $GITHUB_WORKSPACE/toolchain
          tar xf ./gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz --strip-components 1 -C $GITHUB_WORKSPACE/toolchain
          rm ./gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz

      - name: Display toolchain info
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          aarch64-none-linux-gnu-gcc --version

      - name: Cache build result for ${{ env.TORCH_VERSION }} ${{ matrix.lib-type }}
        id: cache-build-result
        uses: actions/cache@v4
        with:
          path: torch-linux-${{ matrix.arch }}-${{ matrix.lib-type }}-v${{ env.TORCH_VERSION }}.tar.bz2
          key: torch-linux-${{ matrix.arch }}-${{ matrix.lib-type }}-v${{ env.TORCH_VERSION }}

      - name: Download PyTorch ${{ env.TORCH_VERSION }}
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          version=${{ env.TORCH_VERSION }}
          curl -SL -O https://github.com/pytorch/pytorch/releases/download/v$version/pytorch-v$version.tar.gz
          tar xf pytorch-v$version.tar.gz

          mv pytorch-v$version torch-$version

          cd torch-$version

          # To fix the following error
          # https://github.com/csukuangfj/torch-libs/actions/runs/9709473947/job/26798232025#step:5:66
          # /usr/bin/ld: /home/runner/work/torch-libs/torch-libs/build/_deps/torch_libs-src/lib/libtorch_cpu.so: undefined reference to `torch::jit::LEGACY_deserialize(std::shared_ptr<torch::jit::CompilationUnit>, std::shared_ptr<caffe2::serialize::PyTorchStreamReader>, std::optional<c10::Device> const&)'

          sed -i.bak s'|^#if !defined(C10_MOBILE) && !defined(C10_DISABLE_LEGACY_IMPORT)|#if 0|'g ./torch/csrc/jit/serialization/import.cpp

          # To fix the following error
          # https://github.com/csukuangfj/torch-libs/actions/runs/9709473947/job/26798232025#step:5:67
          # /usr/bin/ld: /home/runner/work/torch-libs/torch-libs/build/_deps/torch_libs-src/lib/libtorch_cpu.so: undefined reference to `torch::jit::writeArchiveAndTensors(std::string const&, char const*, unsigned long, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, caffe2::serialize::PyTorchStreamWriter&)'
          sed -i.bak s'|^#ifndef C10_MOBILE|#if 0|'g ./torch/csrc/jit/serialization/pickle.cpp

      - name: Build torch ${{ env.TORCH_VERSION }} for ${{ matrix.arch }}
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          aarch64-none-linux-gnu-gcc --version

          version=${{ env.TORCH_VERSION }}
          cd torch-$version

          uname -a
          gcc --version
          python3 --version
          python3 -m pip install ninja cmake
          cmake --version

          ls -lh
          pip install -r ./requirements.txt
          if [[ ${{ matrix.lib-type }} == "shared" ]]; then
            BUILD_SHARED_LIBS=ON
          else
            BUILD_SHARED_LIBS=OFF
          fi

          mkdir build
          cd build
          echo "----"
          echo "pwd: $PWD"
          ls -lh
          echo "----"

          # see https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html
          cmake \
            -D CMAKE_SYSTEM_PROCESSOR=aarch64 \
            -D CMAKE_SYSTEM_NAME=Linux \
            -D CMAKE_C_COMPILER=aarch64-none-linux-gnu-gcc \
            -D CMAKE_CXX_COMPILER=aarch64-none-linux-gnu-g++ \
            -D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
            -D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
            -D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
            -D CMAKE_CROSSCOMPILING=ON \
            \
            -D PYTHON_EXECUTABLE=$(which python3) \
            -D CMAKE_INSTALL_PREFIX="./install" \
            -D CMAKE_BUILD_TYPE=Release \
            -D BUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
            -D BUILD_CAFFE2_OPS=OFF \
            -D BUILD_CUSTOM_PROTOBUF=ON \
            -D CAFFE2_LINK_LOCAL_PROTOBUF=ON \
            -D BUILD_LITE_INTERPRETER=OFF \
            -D BUILD_PYTHON=OFF \
            -D INTERN_BUILD_MOBILE=ON \
            -D INTERN_DISABLE_AUTOGRAD=ON \
            -D INTERN_DISABLE_ONNX=ON \
            -D USE_CUDA=OFF \
            -D USE_NCCL=OFF \
            -D USE_DISTRIBUTED=OFF \
            -D USE_ITT=OFF \
            -D USE_KINETO=OFF \
            -D USE_LITE_INTERPRETER_PROFILER=OFF \
            -D USE_MKLDNN=OFF \
            -D USE_MPS=OFF \
            -D USE_NUMPY=OFF \
            -D USE_OPENMP=OFF \
            -D USE_SOURCE_DEBUG_ON_MOBILE=OFF \
            -D USE_XNNPACK=OFF \
            -D USE_NNPACK=OFF \
            \
            -D USE_VALGRIND=OFF \
            ..

          make -j $(nproc) install


      - name: Display results
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd torch-${{ env.TORCH_VERSION }}

          sudo chown -R $USER ./build

          ls -lh build/install

          cd build

          dst=torch-linux-${{ matrix.arch }}-${{ matrix.lib-type }}-v${{ env.TORCH_VERSION }}

          cd install
          ls -lh

          if [[ ${{ matrix.lib-type }} == 'static' ]]; then
            cp -av ./lib64/* ./lib/ || true
          fi

          rm -rf lib64

          cd ..

          mv install $dst

          tar cjvf $dst.tar.bz2 $dst

          mv $dst.tar.bz2 ../..

      - uses: actions/upload-artifact@v4
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        with:
          name: torch-linux-${{ matrix.arch }}-${{ matrix.lib-type }}-v${{ env.TORCH_VERSION }}
          path: ./*.tar.bz2

      - name: Publish to huggingface
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false

            ls -lh

            git clone https://huggingface.co/csukuangfj/torch-libs huggingface
            cd huggingface
            git pull

            name=torch-linux-${{ matrix.arch }}-*.tar.bz2

            cp -v ../$name .

            git status
            git add .
            git commit -m "add $name"
            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/torch-libs main
